sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t pravib/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true pravib/docker-react npm run test -- --coverage